### ISSUE TITLE
Update 'No User Found' error message

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#100]
**[0.5]**

Observed
----

* Login to SMART
* Select Search option
* Enter any random letters
* click search
* 'No User Found' error message appears after several moments

Expected
----

* Login to SMART
* Select Search option
* Enter any random letters
* click search
* 'No Service User with those details found. Please check the details you entered.'

**Comment by otormaigh** [comment]
How does this look?

![device-2015-05-30-170924](https://cloud.githubusercontent.com/assets/10416394/7898153/cfc292e0-06ee-11e5-84a1-5915ba0a4352.png)

**Comment by Wogiebear** [comment]
What: issue scrub
When 05-Jun-2015
Who: Elliot, Conor

##### Feedback

* Update the text "No Service User found with those details. Try again."
* Reduce the font size.

**Comment by otormaigh** [comment]
Changed error message.
![device-2015-06-05-163952](https://cloud.githubusercontent.com/assets/10416394/8009558/9532c3fe-0ba1-11e5-967b-bb6574a3bc9a.png)
