### ISSUE TITLE
Midwife notes [DRAFT]

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#101]
Background
----

Midwives add and contribute short notes on patients. Over the course of a pregancy, multiple midwives may have contributed notes to a patient's record. These notes are important communication tools for the midwives, a way of sharing their observations about the patient with each other.

Currently the Midwives Notes under the Post-natal tab of a patient's record does nothing. We need to get exact requirements for this.

This issue will track this.

**Comment by marjaimate** [comment]
https://github.com/TheProductWorks/smart_client/issues/113 and https://github.com/TheProductWorks/smart_client/issues/112 caters for these
