### ISSUE TITLE
Update placeholder styling

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#102]
**[0.5]**

Placeholder text in fields are styled very similarly to labels and actual valid data.
This may cause confusion for the midwife..

Update the styles such that fields with no data should show a placeholder hint.
The placeholder hint text should be:

 * Italic
 * Light grey
 * Same size as field label font.

![screenshot_2015-05-21-16-41-11 1](https://cloud.githubusercontent.com/assets/8091781/7752688/d0925506-ffd8-11e4-97fe-9344a7b8a11f.png)

**Comment by GH8734** [comment]
![device-2015-05-22-143329](https://cloud.githubusercontent.com/assets/10416394/7771496/b3a27798-008f-11e5-8bb4-d82d32c07a0c.png)

Check out this.

So I changed text style to italics. As for colours. The first is the lightest, second up a shade and third is the original.

**Comment by Wogiebear** [comment]
What: issue scrub
When: Fri, 05-Jun-2015
Who: Elliot, Conor

##### Feedback

* Apply colour #A9A9A9 to all field hints
* Apply italics to all field hints.

**Comment by otormaigh** [comment]
Change text colour and text style of all EditTexts
![device-2015-06-05-163736](https://cloud.githubusercontent.com/assets/10416394/8009534/5a3c5788-0ba1-11e5-9909-5be0bc6ef3e3.png)
