### ISSUE TITLE
Add functionality to mark an appointment as attended or not

### ISSUE THREAD

**Issue by sciritai** [TheProductWorks/smart_client#104]
Story
------

As a midwife I want to be able to record the fact that one of my appointments did attend the apointment.

Tasks
------

API doc is updated here: https://github.com/TheProductWorks/smart_client/blob/master/doc/api.md#put-appointmentsappointment_id

Add a button that makes a PUT request to as described in the doc to make attended be true. See example screenshot here:

![screen shot 2015-05-28 at 13 20 18](https://cloud.githubusercontent.com/assets/1171007/7859877/56f10abc-053c-11e5-81bd-3fb897f2674d.png)

**Comment by otormaigh** [comment]
Added ability to slide item in list to reveal hidden options that allow the user to mark appointment as attended. When marked as attended the status indicator changes from red (not attended) to green (attended)
![device-2015-06-01-130634](https://cloud.githubusercontent.com/assets/10416394/7912447/719dc212-085f-11e5-8259-bc437b4455c9.png)

**Comment by Wogiebear** [comment]
What: Issue scrub
Who: Elliot, Conor
When: Fri 05-Jun-2015

##### Feedback

* Slide left works well
* Some confusion between clicking a record to slide left and clicking to open patient detail. Goal: add long press to a record to retrieve patient record
* Make attended flag on free slot a light grey or empty box
* Disable slide left on free slot
* Remove dashed line on free slot
* Green style of Free Slot appears a little blurry. Aim: bold and remove shadow.
* Need to be able to go from "attended" to "not attended".

**Comment by otormaigh** [comment]
* Disable swipe on free slot
* Removed shadow from free slot
* Removed dashes from free slot
![device-2015-06-05-162748](https://cloud.githubusercontent.com/assets/10416394/8009315/e4a85e00-0b9f-11e5-9d55-38bca2d7dbf1.png)

* Changed default indicator to light grey

**Comment by otormaigh** [comment]
Added long click to item in appointment list.
