### ISSUE TITLE
Home Visits: prototype a flow for making a home visit

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#111]
Background
----

The CM team make daily home visits to service users. The SMART app has been built to-date to accommodate scheduled clinic appointments. We need to put together a flow for home visits so we can see can the current data model accommodate the needs of home visits.

The goal
----

Prototype a working flow for viewing and making home visits.
(This will be used to nail the requirements with Teresa).

Best Guess User Flow
-----

* Service Provider logs in
* Service Provider selects Home Visits
* Service Provider is presented with a list of Service Options. For this prototype, Service Options should be geographical areas: Dublin South East, Dublin South West, Wicklow North, Wicklow South.
* Service Provider selects a Service Option
* Service Provider is presented with a list of dates to select. Each date will represent a day (not a week, as used in Clinic appointments). Max to show would be the current week of days.
* Service Provider selects a day and is presented with an unordered list of Service Users pencilled in for that date. 
* Each list item shows the following summary information:
  * Service User name
  * Service User address line 1 & town
  * Service User gestation
  * Attended or not attended status flag

**Comment by marjaimate** [comment]
@Wogiebear prototype flow is up and running on http://54.72.7.91/#/service_options/6

Example home visit service options:
* Dublin South Home Visit
* Wicklow North Home Visit

**Comment by marjaimate** [comment]
TODO from demo:
-[] error on modal view
-[] some error in the console about id
-[] check why the service provider is missing in some cases from the modal when creating appointments

**Comment by marjaimate** [comment]
closing, superseeded by [this trello card](https://trello.com/c/xX128gRE/113-home-visits)
