### ISSUE TITLE
Pregnancy logs - log notes from midwifes during appointments

### ISSUE THREAD

**Issue by marjaimate** [TheProductWorks/smart_client#112]
Story
====

* As a service provider, I would like to record pregnancy notes during an appointment
* As a service provider I would like to see notes from previous visits attached to the pregnancy
* As the SMART system,  I can add in log items, such as 'blood requested' to the notes

Acceptance criteria
===============

* Service provider can pull up a service user/pregnancy/appointment card and see previous notes on the pregnancy
* Service provider can add a new note on the pregnancy
* Pregnancy notes are:
 * Persisted in the backend
 * 140 character string field for notes
 * Linked to the pregnancy (indirectly to the service user)
 * Linked to the service provider
 * Timestamped

Technical requirements
==================

* Create a table and related model to hold pregnancy logs
* Setup the necessary relations to the entities mentioned above
* Open APIs on the pregnancy:
 * GET /pregnancies/:ID/notes - get all notes, ordered by time ascending (most recent first)
 * POST /pregnancies/:ID/notes - create note

**Comment by Wogiebear** [comment]
@marjaimate looks like a good starting definition. 

* Let's limit the notes to 140 characters per record. It will encourage brevity. We may have to extend it but a good starting point.
* This should be almost an internal service or helper to the rest of the system... i.e. any action can fire an entry into the log, not just manual note entry from Midwives. For example, conceiveably, we could hook in the 'attended' button to record that a mother attended a clinic. Or, more likely, clicking an action like 'Full Bloods' would log an entry there too.
* Should the GET order the notes in date descending by default?

**Comment by marjaimate** [comment]
@Wogiebear 

* order - yeah, we can always serve date/time ascending. clients can reverse if needed.
* agreed on the action fire, I'll update the description
