### ISSUE TITLE
App: change UI on slide left to mark appointment attended

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#117]
Observed
----

* Go to appointment view
* Select a valid appointment
* Point, hold and slide left
* Background colour is red with white button

Expected
----

* Go to appointment view
* Select a valid appointment
* Point, hold and slide left
* Background colour is #B2DFDB. Text is black. Button colour as green CTA: #43A047 with button text capitlized and white.

**Comment by otormaigh** [comment]
Done. 

![device-2015-06-12-143945](https://cloud.githubusercontent.com/assets/10416394/8131255/f960bf38-1110-11e5-9c06-de2ee27a1b7c.png)
