### ISSUE TITLE
Update date controls on appointment view

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#118]
Observed
-----

* Login as valid user
* Go to appointment view
* Date controls at the top consist of: 
  Current date in central button. Button is salmon pink with black text.
  Next and previous button are grey with black text
![lwegwgu](https://cloud.githubusercontent.com/assets/8091781/8131055/909b81aa-110f-11e5-9bfb-1b8ae9e9c216.jpg)

Expected
-----

* Login as valid user
* Go to appointment view
* Date controls at the top consist of
  - Central button: 
    - Current date in central button. Button is #B2DFDB colour with black text.
    - Use Icon BEFORE the text: https://www.google.com/design/icons/index.html#ic_expand_more
  - Prev button
    - grey background with black text
    - User icon BEFORE the text: https://www.google.com/design/icons/index.html#ic_chevron_left
  - Next button
    - grey background with black text
    - User icon AFTER the text: https://www.google.com/design/icons/index.html#ic_chevron_right

**Comment by otormaigh** [comment]
Done.

![device-2015-06-17-113420](https://cloud.githubusercontent.com/assets/10416394/8205049/f4e432e6-14e4-11e5-8640-836a1c4cc625.png)
