### ISSUE TITLE
Update colors of 'attended' indicators

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#119]
Observed
-----

* Login as valid user
* Go to appointment view for any day with appointments
* Unattended slots have a deep red color solid flag on right hand side
* Attended slots have a bright green colour solid flag on right hand side
* Free slots have a dark grey colour solid flag on right hand side

Expected
-----

* Login as valid user
* Go to appointment view for any day with appointments
* Unattended slots have a #FFCC80 color solid flag on right hand side
* Attended slots have a #26A69A green colour solid flag on right hand side
* Free slots have a 'very light grey' colour border with empty filling (white) on right hand side

**Comment by otormaigh** [comment]
Done.

![device-2015-06-12-150833](https://cloud.githubusercontent.com/assets/10416394/8131835/011a2c42-1115-11e5-922b-6f6af9f21715.png)
