### ISSUE TITLE
"Free slot" colour

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#120]
Observed
----

* Login as valid user
* Open appointment view for day with any valid appointments
* Free slots are shown with label "Free slot" and bright green font colour

Expected
----

* Login as valid user
* Open appointment view for day with any valid appointments
* Free slots are shown with label "Free slot" and #81C784 font colour

**Comment by otormaigh** [comment]
Done.

![device-2015-06-12-150315](https://cloud.githubusercontent.com/assets/10416394/8131741/4676d930-1114-11e5-876e-28a95627f4b1.png)
