### ISSUE TITLE
Handling of Anti D fields

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#121]
What: review of first version
Where: BoI
Who: Elliot, Conor

- [x] Standardise wording... always use "Anti-D". Replace all instances of "Anti D" or AntiD"
- [x] Add a close icon to the general popup dialog. Big X in top right hand title bar. Note: keep the header text centred. Should appear on both 'Anti-D history' and 'select option' popups. 
- [x] On 'Select an option" dialog, update header text to "Select an Anti-D option"
- [x] On 'Select an option" dialog, update CTA from "ADD TO ANTI D HISTORY" -> "SAVE OPTION"   
- [x] Remove 'Anti D History'
- [x] Add history icon to the right of the field setting in 'Anti D' line.

**Comment by otormaigh** [comment]
All Done

**Comment by Wogiebear** [comment]
[Review]

Values aren't saving in the UI due to 500 response to POST request. Value is being commited to the database, nonetheless.

Need to troubleshoot with @marjaimate, @sciritai 

@marjaimate @sciritai:

Looks like an errant typo in the update query... check out _'feeding': u'None'_ in the below log extract...

```
[Wed Jun 24 10:18:25.827780 2015] [:error] [pid 27778] [client 93.94.115.102:57848] DataError: (DataError) invalid input value for enum feeding: "None"
[Wed Jun 24 10:18:25.827834 2015] [:error] [pid 27778] [client 93.94.115.102:57848] LINE 1: ...ed_at, pregnancy_id, service_provider_id) VALUES ('None', '2...
[Wed Jun 24 10:18:25.827870 2015] [:error] [pid 27778] [client 93.94.115.102:57848]                                                              ^
[Wed Jun 24 10:18:25.827904 2015] [:error] [pid 27778] [client 93.94.115.102:57848]  'INSERT INTO feeding_history (feeding, created_at, pregnancy_id, service_provider_id) VALUES (%(feeding)s, %(created_at)s, %(pregnancy_id)s, %(service_provider_id)s) RETURNING feeding_history.id' {'created_at': datetime.datetime(2015, 6, 24, 10, 18, 25, 818941), 'feeding': u'None', 'service_provider_id': 14, 'pregnancy_id': 12}
```

**Comment by otormaigh** [comment]
500 errors fixed
