### ISSUE TITLE
App changes to Midwives Notes

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#123]
What: Review of app
Where: BoI
Who: Conor, Elliot

- [x] Rename field label to "Midwifery Log"
- [x] Change style of label to match all existing line labels (light grey, etc.)
- [x] Value should be fixed to 'View' with history icon to the right.
- [x] clicking the entire line will load the notes
- [x] Notes view has title of "Midwifery Log"
- [x] each line item should be: timestamp, author, log entry. Timestamp and author are a sub-heading and the note appears below.
- [x] notes separated by light grey line
- [x] Secondary CTA is 'Add Note'
- [x] Clicking Secondary CTA loads a new popup in which user can type a note with keyboard. New popup contains 'Save Note' CTA
- [x] Ensure there is a clear 'close' icon or button always visible on each step

**Comment by otormaigh** [comment]
Done.

![device-2015-06-18-223554](https://cloud.githubusercontent.com/assets/10416394/8242991/3a5be2d4-160b-11e5-81e9-1619f7dd95c1.png)
![device-2015-06-18-224051](https://cloud.githubusercontent.com/assets/10416394/8242992/3a6342f4-160b-11e5-9f34-d452cda8a321.png)
