### ISSUE TITLE
Appointment confirmation step: make into a popup dialog

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#124]
## Observed
- Login as valid service provider
- Go to Appointments
- Select a free slot
- Enter all valid appointments details and click [Confirm Appointment]
- Service Provider sees a new page:
  - Title = "SMART"
  - all booking details
  - Book and Cancel buttons
## Expected
- Login as valid service provider
- Go to Appointments
- Select a free slot
- Enter all valid appointments details and click [Confirm Appointment]
- Service Provider sees a popup dialog that follows the style convention of other dialogs:
  - Title = "Confirm Details"
  - all booking details: labels in grey, values in normal font weight and style
  - Book as full width CTA (green button)
  - Cancel button as full width NCTA) grey

**Comment by otormaigh** [comment]
- [x] Show address in 'To Attend' field in confirm appointment details

**Comment by otormaigh** [comment]
![device-2015-07-01-114815](https://cloud.githubusercontent.com/assets/10416394/8452921/2de8015a-1fe7-11e5-9002-b15faa3949fd.png)
