### ISSUE TITLE
Update the 'Home' icon

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#97]
Background
------

Users can click top left corner of app to get back to the 'home' screen.

Observed
-----

* Midwife sees arrow icon in top left hand of action bar
* midwife clicks this arrow icon to go back to previous page

Expected
----

* Midwife sees 'hamburger' icon in top left hand of action bar
* midwife clicks the icon to go back to the home screen.

**Comment by GH8734** [comment]
![device-2015-05-21-213745](https://cloud.githubusercontent.com/assets/10416394/7758438/a5f3e354-0001-11e5-8b67-a2362734fe8f.png)

Changed back arrow to 'hamburger' icon. See attached screenshot.

**Comment by Wogiebear** [comment]
Looks better alright... user isn't going to think they're going 'back'. One point, can you get the title in the action bar to be centred? It's slightly left-aligned

**Comment by GH8734** [comment]
I'll have a go at it now.

**Comment by GH8734** [comment]
![device-2015-05-22-135814](https://cloud.githubusercontent.com/assets/10416394/7770950/6a03a142-008b-11e5-958a-06b066efa5ec.png)
![device-2015-05-22-140214](https://cloud.githubusercontent.com/assets/10416394/7770951/6a06761a-008b-11e5-97d3-7851737b74c2.png)

Text is now centred. How does it look?
