### ISSUE TITLE
Clicking hamburger icon opens nav drawer

### ISSUE THREAD

**Issue by Wogiebear** [TheProductWorks/smart_client#98]
**[1.5]**

Background
----

Currently clicking the hamburger icon brings the user back to the home screen.
It's more conventional for android that clicking the hamburger causes a nav drawer to slide out from left.

Observed
-----

* Midwife is on any screen
* midwife clicks hamburger menu in top left hand action bar
* midwife is brought to home screen with primary feature options:
  * Search patient
  * book appointment
  * calendar
  * today's appointments

Expected
----
* Midwife is on any screen
* midwife clicks hamburger menu in top left hand action bar
* nav drawer slides out wih midwife is brought to home screen with primary feature options
  * Search Patient
  * Book Appointment
  * Calendar
  * Today's Appointments
  * Sync Data
  * Logout

**Comment by otormaigh** [comment]
![device-2015-05-25-105328](https://cloud.githubusercontent.com/assets/10416394/7795443/086bbc6e-02cd-11e5-9136-6679293fccaf.png)
![device-2015-05-25-105336](https://cloud.githubusercontent.com/assets/10416394/7795444/086d59ac-02cd-11e5-965f-046e48675713.png)
![device-2015-05-25-105343](https://cloud.githubusercontent.com/assets/10416394/7795445/087a53a0-02cd-11e5-9d3a-31ab8e1cc549.png)

This is done. Just need to clean up the layout, it is very rough at the moment.

I also added some animation to the 'hamburger' when you slide out the navigation drawer (see screenshots)

**Comment by Wogiebear** [comment]
What: issue scrub
When: Fri 05-Jun-2015
Who: Elliot, Conor

Observations
----


- When selecting another menu item, the drawer closes. The transition when closing is slightly  'stuttering'.

**Comment by otormaigh** [comment]
Made the animation when the navigation drawer closes smoother.
